#define MAJOR 0
#define MINOR 0
#define PATCH 0
#define BUILD 765


// #define VERSION MACROS
#define VERSION MAJOR.MINOR
#define VERSION_AR MAJOR,MINOR,PATCH,BUILD
#define VERSION_STR MAJOR##.##MINOR##.##PATCH##.##BUILD

#define REQUIRED_VERSION 2.18
