[default]
workshop = [
    "450814997",  # CBA_A3's Workshop ID
    "463939057",  # ACE3
    "2369477168", # Advanced Developer Tools
    "1779063631", # ZEN
    "3355988282", # CVO Media
]

dlc = []
optionals = []

parameters = [
    "-window",
    "-noPause",
    "-noPauseAudio",
]

[Debugger]
extends = "default"
workshop = [
    "1645973522", # Intercept Minimal Dev
    "1585582292", # Arma Debug Engine
]


[Stratis]
extends = "default"
dlc = ["ws","rf"]
mission = "Stratis.Stratis"


[GreenMag]
extends = "Stratis"
workshop = ["2352603233"] # Greenmag

[VR]
extends = "default"
mission = "exec.VR"

[airlift]
extends = "default"
mission = "airlift.VR"

[rockslide]
extends = "default"
mission = "rockslide.Tanoa"

[bigBoom]
extends = "default"
mission = "bigBoom.Altis"

[ula]
extends = "default"
mission = "ULA-Dedicated-MP-Test.stratis"

[CSC]
# extends = "default"
extends = "default"
mission = "CSC.Altis"