[default]
workshop = [
    "450814997",  # CBA_A3's Workshop ID
    "463939057",  # ACE3
    "3499977893", # Advanced Developer Tools
    "1779063631", # ZEN
    "3355988282", # CVO Media
]

dlc = []
optionals = []

parameters = [
    "-window",
    "-noPause",
    "-noPauseAudio",
]

[debugger]
extends = "default"
workshop = [
    "1645973522", # Intercept Minimal Dev
    "1585582292", # Arma Debug Engine
]


[stratis]
extends = "default"
dlc = ["ws","rf"]
mission = "Stratis.Stratis"

[intel]
extends = "default"
mission = "intel.VR"

[greenmag]
extends = "stratis"
workshop = ["2352603233"] # Greenmag

[test]
extends = "default"
mission = "exec.VR"

[vr]
extends = "default"
mission = "VR.VR"

[airlift]
extends = "default"
mission = "airlift.VR"

[rockslide]
extends = "default"
mission = "rockslide.Tanoa"

[bigboom]
extends = "default"
mission = "bigBoom.Altis"

[ula]
extends = "default"
mission = "ULA-Dedicated-MP-Test.stratis"

[csc]
extends = "default"
mission = "CSC.Altis"

[arsenal]
extends = "default"
mission = "Arsenal.Altis"

[deploy]
extends = "default"
mission = "Deploy.Altis"

[ambient]
extends = "default"
mission = "ambient.VR"
