name = "24th Chorni Voron - Auxiliary Mod"
prefix = "cvo"

mainprefix = "z"

[files]
include = [
    "mod.cpp",      # These files are copied to the build directory by default
    "meta.cpp",     # They do not need to be added to your list
    "LICENSE",
    "logo_ca.paa",
    "logo_co.paa",
]
exclude = [
    "*.psd",        # By default this list is empty
    "*.md",
    ".vscode",
]

[version]
major = 0 # Overrides path when set
minor = 0
patch = 1
build = 1 # Optional

[properties]
author = "CVO Team - Mr. Zorn"
url = "https://github.com/PulsarNeutronStar/CVO-Auxiliary"

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3

]

dlc = [
]

optionals = [
]

parameters = [
    "-skipIntro",           # These parameters are passed to the Arma 3 executable
    "-noSplash",            # They do not need to be added to your list
    "-showScriptErrors",    # You can add additional parameters here
    "-debug",
    "-filePatching",
    "-window",
]

executable = "arma3_x64"        # Default: "arma3_x64"
